api/urls.py
from rest_framework import routers
from api.views import *

from django.urls import path, include

router = routers.DefaultRouter()   # 인스턴스 생성

# SensorViewSet이 ./api/sensor/와 ./api/sensor/<int:id>/ 2개를 등록해 (id 있는거 없는거)
router.register('sensor', SensorViewSet, basename='sensor')    # sensor를 기본 url로 등록 / View 클래스 등록
router.register('cds', CDSViewSet, basename = 'cds')
router.register('temp', TempViewSet, basename = 'temp')
router.register('humid', HumiViewSet, basename = 'humid')

router.register('curtain', CurtainViewSet)
router.register('curtain_time', CurtainTimeViewSet)
router.register('doorlock', DoorlockViewSet)

router.register('aircon', AirconViewSet)
router.register('heater', HeaterViewSet)
router.register('humidifier', HumidifierViewSet)
router.register('dehumidifier', DehumidifierViewSet)

router.register('standard_temp', StandardTemperatureViewSet) #
router.register('standard_humi', StandardHumidityViewSet) 
router.register('total_control', TotalSmartControlViewSet) 

router.register('secfile', SecFileViewSet, basename='secfile')
router.register('imgfile', ImgFileViewSet, basename = 'imgfile')


urlpatterns = [
    path('', include(router.urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('iot/', include('iot.urls')),
    path('mjpeg/', include('mjpeg.urls')),
    path('kakao/', include('kakao.urls')),
    path('api/', include('api.urls')),         # django rest framework
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('mqtt/', TemplateView.as_view(template_name = 'iot/mqtt.html'), name = 'mqtt'),
    path('intrusion/', detect_intrusion),       # 카톡으로 메세지 보내기

    path('sec_upload/', sec_upload, name = 'sec_upload'),   # secfile 업로드
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name = 'detail'),

    path('img_upload/', img_upload, name = 'img_upload'),   # imgfile 업로드

]

iot/models.py
from django.db import models
from django.utils import timezone

# 지금은 편의를 위해 사용자 계정 연동 항목을 뺌 - 프로젝트할때는 넣으면 좋음
class Sensor(models.Model):
    place = models.CharField(max_length = 50)   # 설치 장소
    category = models.CharField(max_length = 50)  # 센서 종류
    value = models.FloatField()                  # 센서 값
    created_at = models.DateTimeField()          # 측정 날짜-시간


class DHT_temp(models.Model):
    place = models.CharField(max_length = 50)   
    value = models.FloatField()        
    created_at = models.DateTimeField()       

class DHT_humi(models.Model):
    place = models.CharField(max_length = 50)   
    value = models.FloatField()                  
    created_at = models.DateTimeField()   


class CDS(models.Model):
    place = models.CharField(max_length = 50)   
    value = models.FloatField()                  
    created_at = models.DateTimeField()    


class SecFile(models.Model):
    file_name = models.CharField(max_length = 100)
    sec_file = models.FileField(upload_to = "sec_file/%Y_%m_%d/")
    # 라즈베리파이에서 upload하면 django 서버에서
    # media/sec_file/에 월별 일별로 파일이 만들어져서 upload돼


class ImageFile(models.Model):
    file_name = models.CharField(max_length = 100)
    img_file = models.FileField(upload_to = "img_file/%Y_%m_%d/")


# 커튼제어 모델
class ControlCurtain(models.Model):
    curtaincontrol = models.BooleanField(default=False)  


class CurtainTime(models.Model):
    time_day = models.DateTimeField()
    time_night = models.DateTimeField()
    

# 도어락제어 모델
class ControlDoorlock(models.Model):
    doorlockcontrol = models.BooleanField(default=False)  



# 에어컨 제어 모델
class ControlAircon(models.Model):
    airconcontrol = models.BooleanField(default=False)  


# 히터 제어 모델
class ControlHeater(models.Model):
    heatercontrol = models.BooleanField(default=False)   


# 가습기 제어 모델
class ControlHumidifier(models.Model):
    humidifiercontrol = models.BooleanField(default=False)   


# 제습기 제어 모델
class ControlDehumidifier(models.Model):
    dehumidifiercontrol = models.BooleanField(default=False)   


# 기준온도 모델     
class StandardTemperature(models.Model): 
    standard_temp = models.FloatField()         


# 기준습도 모델     
class StandardHumidity(models.Model): 
    standard_humi = models.FloatField() 


class TotalSmartControl(models.Model) : 
    total_control = models.BooleanField(default=False)

iot/views.py
from django.shortcuts import render
from . import sub
from django.views.generic import TemplateView
from django.http import JsonResponse   # Json으로 응답
from django.views.decorators.csrf import csrf_exempt
from .models import SecFile, ImageFile
from django.views import generic

@csrf_exempt   # csrf token 없이
def sec_upload(request):
    if request.method == 'POST':
        file_name = request.POST['file_name']
        sec_file = request.FILES['sec_file']
        model = SecFile(file_name = file_name, sec_file = sec_file)
        model.save()
        print('upload file', file_name, sec_file)
        msg = {'result' : 'success'}

    else:                                # GET 요청
        msg = {'result' : 'fail'}
    return JsonResponse(msg)


@csrf_exempt   # smartCam - 20cm이내로 오면 2초동안 사진 5번 촬영하는 기능용
def img_upload(request):
    if request.method == 'POST':
        file_name = request.POST['file_name']
        img_file = request.FILES['img_file']
        model = ImageFile(file_name = file_name, img_file = img_file)
        model.save()
        print('upload file', file_name, img_file)
        msg = {'result' : 'success'}

    else:                                # GET 요청
        msg = {'result' : 'fail'}
    return JsonResponse(msg)


def send_talk(text, url):
    talk_url = "https://kapi.kakao.com/v2/api/talk/memo/default/send"
    with open("access_token.txt", "r") as f:
        token = f.read()
    header = {"Authorization": f"Bearer {token}"}

    # 문자열 하나, 링크 하나로 구성되는 카톡 메시지 구성
    text_template = {
        'object_type': 'text',
        'text': text,
        'link': {
                'web_url': url,
                'mobile_web_url' : url
        }
    }

def detect_intrusion(request):
    # 카톡으로 메세지 보내기
    text = request.GET.get('text')
    url = request.GET.get('url')

    res = send_talk(text, url)
    if res.get('result_code') == 0:
        msg = {'result' : 'success'}
    else:
        msg = {
            'result' : 'fail',
            'reason' : str(res),
        }
    return JsonResponse(msg)


# 녹화 파일 목록 보기
class SecFileListView(generic.ListView):
    model = SecFile
    template_name = 'iot/sec_file_list.html'
    context_object_name = 'sec_files'


# 녹화 파일 상세 보기
class SecFileDetailView(generic.DetailView):
    model = SecFile
    template_name = 'iot/sec_file_detail.html'
    context_object_name = 'vfile'


templates/iot/mqtt.html
{% extends 'base.html' %}
{% block content %}

<div class="ml-3 mt-3">
    <h5>
        <i class="fa-solid fa-upload"></i>&nbsp;
        Publish
    </h5>
    <p>Topic: <input type="text" id = "topic" class="mt-1 ml-4"/></p>
    <p>message: <input type="text" id = "message"/></p>
    <button type="button" class="btn btn-info btn-sm ml-1 mt-1" id = "publish-btn">Send</button>
</div>

<br><hr>

<div class="ml-3">
    <h5>
        <i class="fa-solid fa-lightbulb" id="led-icon"></i>
        Livingroom Led
    </h5>
    <div class = "custom-control custom-switch mt-3">  <!-- 스위치 정의 -->
        <input type="checkbox" class = "custom-control-input" id="led">  <!--스위치의 상태를 나타냄, 라벨과 연결-->
        <label class="custom-control-label" for="led" id="led-label">On</label>  <!-- for을 id와 일치시켜 -->
    </div>
</div>

<br><hr>

<div class="ml-3">
    <h5>
        <i class="fa-solid fa-house-signal"></i>
        Current Status
    </h5>
    <div class="mt-3">
        <i class="fa-regular fa-sun"></i>
        Illuminance: <span id = "illu"></span>
    </div>
    <div class="mt-1">
        <i class="fa-solid fa-temperature-three-quarters"></i>
        Temperature: <span id = "temp"></span> °C
    </div>
    <div class="mt-1">
        <i class="fa-solid fa-droplet"></i>
        Humidity: <span id="humi"></span> %
    </div>
</div>

{% endblock %}

{% block script %}
<!-- MQTT 라이브러리 로드 -->
<script
    src = "https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js"
    type = "text/javascript" >
</script>

<script>    
    const BROKER_IP = 'localhost';
    const BROKER_PORT = 9001;
    const CLIENT_ID = 'clientID-' + parseInt(Math.random() * 100);    // 랜덤 아이디
    const SUBSCRIBE_TOPIC = 'iot/sensor/#';

    client = new Paho.MQTT.Client(BROKER_IP, BROKER_PORT, CLIENT_ID);
    console.log(BROKER_IP, BROKER_PORT, CLIENT_ID);

    let btn = document.getElementById('publish-btn');
    let inputTopic = document.getElementById('topic');
    let inputMessage = document.getElementById('message');
    let led = document.getElementById('led');

    // // let illu = document.getElementById('illu');
    // // let temp = document.getElementById('temp');
    // // let humi = document.getElementById('humi');

    // 브라우저에서 MQTT를 통해 IoT 장치를 제어
    led.onchange = () => {       // 스위치의 상태가 변경될 때마다 실행
        console.log(led.checked);   // 스위치 체크상태 확인 -> 누르면 true/false 나옴

        let value = led.checked ? 'on' : 'off';
        const message = new Paho.MQTT.Message(value);   // MQTT 메시지를 만들고 전송
        
        message.destinationName = 'iot/control/led';    // MQTT 메시지를 전송할 주소
        client.send(message);    // MQTT 메시지를 서버로 보냄

        let icon = document.getElementById('led-icon');  // 전등 아이콘의 DOM 요소를 가져와
        let label = led.parentElement.querySelector('.custom-control-label');
        // 전등의 라벨 요소를 가져와

        if(led.checked) {
            icon.classList.add('text-warning');   // 전등 아이콘 클래스에 text-warning 클래스 추가(노랑색)
            label.innerText = "On";               // 라벨 텍스트 on으로 변경
        } 
        else {
            icon.classList.remove('text-warning');
            label.innerText = "Off";
        }
    };
    
    let sensors = {
        illu : document.getElementById('illu'),
        temp : document.getElementById('temp'),
        humi : document.getElementById('humi'),
    };

    let historyValues = {
        illu: [],
        temp: [],
        humi: [],
    };

    client.onConnectionLost = onConnectionLost;  // 연결 끊김 콜백
    client.onMessageArrived = onMessageArrived;   // 메세지 도착 콜백
    console.log("connecting.....")
    client.connect({
        onSuccess: onConnect,   // 연결 성공시 호출 콜백
        onFailure: onFailure,   // 연결 실패시 호출 콜백
    });

    function onConnectionLost(responseObject) {
        if (responseObject.errorCode !== 0) {
            console.log('onConnectionLost:' + responseObject.errorMessage);
        }
    }

    function onMessageArrived(message) {
        console.log('topic:' + message.destinationName);  // temp인지 illu인지 humi인지
        console.log('message:' + message.payloadString);  // 센서값 출력

        let parts = message.destinationName.split('/');
        console.log(parts);
        let category = parts.at(-1);       // 맨 마지막 요소를 추출

        //if(category == "illu") {
        //    illu.innerText = message.payloadString;
        //}
        //else if (category == "temp") {
        //    temp.innerText = message.payloadString;
        //}
        //else if(category == "humi") {
        //    humi.innerText = message.payloadString;
        //}

        if (sensors[category]) {
            sensors[category].innerText = message.payloadString;
            historyValues[category].push(message.payloadString);   // 배열의 끝에 추가 push
            console.log(category, historyValues[category]);
        } 
        else {    
            console.log("잘못된 카테고리입니다.", category);
        }
    }
    
    function onFailure() {
        alert('Please enter host and port again.');
    }

    function onConnect() {
        console.log('onConnect');
        client.subscribe(SUBSCRIBE_TOPIC);
    }

    btn.onclick = () => {
        // alert('click');   // 동작 확인용 (메세지를 띄움)
        const topic = inputTopic.value;
        const message = new Paho.MQTT.Message(inputMessage.value);
        
        message.destinationName = topic;
        message.qos = 1;
        client.send(message);
    };
</script>
{% endblock %}

templates/iot/sec_file_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- 리스트 항목을 눌렀을 때 재생되는 영상 -->
<h2>
    <i class="fa-solid fa-video mt-3 ml-3"></i>
    보안 카메라 녹화 영상
</h2>
<hr>

<h5 class = "ml-3 mt-2">
    {{vfile.file_name}}
</h5>

<video controls class = "ml-3 mt-2">
    <source src = "/media/{{ vfile.sec_file }}" type = "video/mp4"/>
</video>
<br>

<a href="{% url 'iot:list' %}" class="btn btn-info ml-3" role="button">List</a>
{% endblock %}

templates/iot/sec_file_list.html
{% extends 'base.html' %}
{% block content %}
<!-- 촬영된 영상 리스트 -->
<h2>
    <i class="fa-sharp fa-solid fa-camera mt-3 ml-3"></i>
    Recorded Videos
</h2>
<hr>
<ul>
    {% for sec_file in sec_files %}
    <li>
        <a href="{% url 'iot:detail' sec_file.id %}">{{ sec_file.file_name }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}