api/urls.py
from rest_framework import routers
from api.views import *

from django.urls import path, include

router = routers.DefaultRouter()   # 인스턴스 생성

# SensorViewSet이 ./api/sensor/와 ./api/sensor/<int:id>/ 2개를 등록해 (id 있는거 없는거)
router.register('sensor', SensorViewSet, basename='sensor')    # sensor를 기본 url로 등록 / View 클래스 등록
router.register('cds', CDSViewSet, basename = 'cds')
router.register('temp', TempViewSet, basename = 'temp')
router.register('humid', HumiViewSet, basename = 'humid')

router.register('curtain', CurtainViewSet)
router.register('curtain_time', CurtainTimeViewSet)
router.register('doorlock', DoorlockViewSet)

router.register('aircon', AirconViewSet)
router.register('heater', HeaterViewSet)
router.register('humidifier', HumidifierViewSet)
router.register('dehumidifier', DehumidifierViewSet)

router.register('standard_temp', StandardTemperatureViewSet) #
router.register('standard_humi', StandardHumidityViewSet) 
router.register('total_control', TotalSmartControlViewSet) 

router.register('secfile', SecFileViewSet, basename='secfile')
router.register('imgfile', ImgFileViewSet, basename = 'imgfile')


urlpatterns = [
    path('', include(router.urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('iot/', include('iot.urls')),
    path('mjpeg/', include('mjpeg.urls')),
    path('kakao/', include('kakao.urls')),
    path('api/', include('api.urls')),         # django rest framework
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('mqtt/', TemplateView.as_view(template_name = 'iot/mqtt.html'), name = 'mqtt'),
    path('intrusion/', detect_intrusion),       # 카톡으로 메세지 보내기

    path('sec_upload/', sec_upload, name = 'sec_upload'),   # secfile 업로드
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name = 'detail'),

    path('img_upload/', img_upload, name = 'img_upload'),   # imgfile 업로드

]

kakao/urls.py
from django.contrib import admin
from django.urls import path
from kakao.views import *

app_name = 'kakao'

urlpatterns = [
    path('login/', KakaoLoginView.as_view(), name = "login"),
    path('oauth/', KakaoAuthView.as_view(), name = "oauth"),
    path('talk/', KakaoTalkView.as_view(), name = "talk"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 4 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (required for Bootstrap 4 JavaScript) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <!-- Popper.js (required for Bootstrap 4 JavaScript) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- Bootstrap 4 JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <!-- main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <title>base.html</title>
  </head>

    <body>
   
     <!-- 네비게이션바 -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <h3>IOT SERVER</h3>
        &nbsp;&nbsp;&nbsp;
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'iot:mqtt' %}">
                <!-- <img src="{% static 'img/mqtt.png' %}" class="d-inline-block"> -->
                <i class="fa-solid fa-mosquito"></i>
                MQTT
              </a>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-atom"></i>
                Django Rest Api
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="http://192.168.35.245:8000/api/">Api Root</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="http://192.168.35.245:8000/api/secfile/">SecFile Data List</a>
                <a class="dropdown-item" href="http://192.168.35.245:8000/api/imgfile/">HaarFile Data List</a>

                <a class="dropdown-item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Sensor API
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/sensor/">Sensors</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/cds/">CDS</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/temp/">Temperature</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/humid/">Humidity</a>
                </div>

                <a class="dropdown-item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  IoT Control
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/curtain/">Curtain</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/doorlock/">Doorlock</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/aircon/">Aircon</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/heater/">Heater</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/humidifier/">Humidifier</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/api/dehumidifier/">Dehumidifier</a>
                </div>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-shield-halved"></i>
                Security Cam
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'iot:list' %}">Recorded Videos</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Real-time Shooting
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="http://192.168.35.245:8000/mjpeg/?mode=snapshot">Snapshot</a>
                  <a class="dropdown-item" href="http://192.168.35.245:8000/mjpeg/?mode=stream">Streaming</a>
                </div>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-comments"></i>
                KakaoTalk
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'kakao:login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'kakao:talk' %}">Send Messages</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>


    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    
    
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block script %}
    
    
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    
</body>
</html>