api/urls.py
from rest_framework import routers
from api.views import *

from django.urls import path, include

router = routers.DefaultRouter()   # 인스턴스 생성

# SensorViewSet이 ./api/sensor/와 ./api/sensor/<int:id>/ 2개를 등록해 (id 있는거 없는거)
router.register('sensor', SensorViewSet, basename='sensor')    # sensor를 기본 url로 등록 / View 클래스 등록
router.register('cds', CDSViewSet, basename = 'cds')
router.register('temp', TempViewSet, basename = 'temp')
router.register('humid', HumiViewSet, basename = 'humid')

router.register('curtain', CurtainViewSet)
router.register('curtain_time', CurtainTimeViewSet)
router.register('doorlock', DoorlockViewSet)

router.register('aircon', AirconViewSet)
router.register('heater', HeaterViewSet)
router.register('humidifier', HumidifierViewSet)
router.register('dehumidifier', DehumidifierViewSet)

router.register('standard_temp', StandardTemperatureViewSet) #
router.register('standard_humi', StandardHumidityViewSet) 
router.register('total_control', TotalSmartControlViewSet) 

router.register('secfile', SecFileViewSet, basename='secfile')
router.register('imgfile', ImgFileViewSet, basename = 'imgfile')


urlpatterns = [
    path('', include(router.urls)),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('iot/', include('iot.urls')),
    path('mjpeg/', include('mjpeg.urls')),
    path('kakao/', include('kakao.urls')),
    path('api/', include('api.urls')),         # django rest framework
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mjpeg/urls.py
from django.urls import path
from mjpeg.views import *

app_name = 'mjpeg'

urlpatterns = [
    path('', CamView.as_view(template_name = 'mjpeg/cam.html')),
    path('snapshot/', snapshot, name='snapshot'),
    path('stream/', stream, name='stream'),
]

mjpeg/views.py
from django.shortcuts import render

from django.views.generic import TemplateView
from django.http import HttpResponse, StreamingHttpResponse
from .cvcam import MJpegStreamCam

mjpegstream = MJpegStreamCam()

class CamView(TemplateView):
    template_name = 'cam.html'    # 랜더링할 템플릿 파일 경로

    def get_context_data(self):    # context 변수 구성
        context = super().get_context_data();       # 디폴트 구성
        context["mode"] = self.request.GET.get("mode", "#")  # 나만의 context 변수 추가
        return context    # return한 context가 render(request, 'cam.html', context)로 들어가는 것
    

def snapshot(request):
    image = mjpegstream.snapshot()
    return HttpResponse(image, content_type="image/jpeg")


def stream(request):
    return StreamingHttpResponse(mjpegstream, 
    content_type='multipart/x-mixed-replace;boundary=--myboundary')

templates/mjpeg/cam.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <!-- <h2>
            <i class="fa-sharp fa-solid fa-camera mt-3 ml-3"></i>
            Real-time Shooting
        </h2>
        <hr> -->
        <a href="?mode=snapshot">
            <i class="fa-solid fa-image ml-3"></i>
            Snapshot
        </a> 
        <a href="?mode=stream">
            <i class="fa-solid fa-video ml-2"></i>
            Stream
        </a>
    </div>
    <br>

    {% if mode == "#" %}
        <img id = "image"/>
    {% elif mode == "snapshot" %}
        <img id = "image" src = "{% url 'mjpeg:snapshot' %}" class="ml-3"/>
    {% elif mode == "stream" %}
        <img id = "image" src = "{% url 'mjpeg:stream' %}" class="ml-3"/>
    {% endif %}
{% endblock %}